spring:
  profiles:
    include: oauth
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug

  security:
    jwt:
      token:
        secret-key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
        expire-length: 864000000
    authorized-redirect-uri: "http://localhost:8080/oauth2/redirect"

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/moa?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/moa?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: live
  datasource:
    url: jdbc:mysql://moa-1.c6gy7w152zdy.ap-northeast-2.rds.amazonaws.com/moa?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: moaroot13
    driver-class-name: com.mysql.cj.jdbc.Driver
