ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-auth]]
== 회원가입/로그인

[[resources-auth-email]]
=== 이메일 체크

operation::auth/email[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-auth-signup]]
=== 회원가입

operation::auth/signup[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-auth-login]]
=== 로그인

operation::auth/login[snippets='http-request,http-response,request-headers,request-fields,response-fields']



[[resources-users]]
== 회원 관리

[[resources-user-find]]
=== 로그인 유저 조회

operation::users/me[snippets='http-request,http-response,request-headers,response-fields']

[[resources-user-update]]
=== 로그인 유저 정보 수정

operation::users/update[snippets='http-request,http-response,request-headers,request-fields']


[[resources-users]]
== 감정 기록 관리

[[resources-user-find]]
=== 감정 기록 생성

operation::record/create[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-user-update]]
=== 감정 기록 조회

operation::record/find[snippets='http-request,http-response,request-parameters,response-fields']
