ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-auth]]
== 회원가입/로그인

[[resources-auth-email]]
=== 이메일 체크
operation::auth/email[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-auth-signup]]
=== 회원가입
operation::auth/signup[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-auth-login]]
=== 로그인
operation::auth/login[snippets='http-request,http-response,request-headers,request-fields,response-fields']



[[resources-users]]
== 회원 관리

[[resources-user-find]]
=== 로그인 유저 조회
operation::users/me[snippets='http-request,http-response,request-headers,response-fields']

[[resources-user-update]]
=== 로그인 유저 정보 수정
operation::users/update[snippets='http-request,http-response,request-headers,request-fields']


[[resources-record]]
== 감정 기록 관리

[[resources-record-create]]
=== 감정 기록 생성
operation::record/create[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-record-daily]]
=== 일일 감정 기록 조회
operation::record/daily[snippets='http-request,http-response,request-headers,request-parameters,response-fields']

[[resources-record-weekly]]
=== 주간 감정 기록 조회
operation::record/weekly[snippets='http-request,http-response,request-headers,request-parameters,response-fields']


[[resources-recommendation]]
== 추천 컨텐츠 관리

[[resources-recommendation-find]]
=== 추천 컨텐츠 조회
operation::recommendation/find[snippets='http-request,http-response,request-headers,request-parameters,response-fields']


[[resources-bookmark]]
== 북마크 관리

[[resources-bookmark-create]]
=== 북마크 추가
operation::bookmark/create[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-bookmark-list]]
=== 북마크 목록 조회
operation::bookmark/list[snippets='http-request,http-response,request-headers,response-fields']

[[resources-bookmark-detail]]
=== 북마크 상세 조회
operation::bookmark/detail[snippets='http-request,http-response,path-parameters,request-headers,response-fields']

[[resources-bookmark-delete]]
=== 북마크 삭제
operation::bookmark/delete[snippets='http-request,http-response,path-parameters,request-headers']
