SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE user RESTART IDENTITY;
TRUNCATE TABLE record RESTART IDENTITY;
TRUNCATE TABLE record_keywords RESTART IDENTITY;
TRUNCATE TABLE emotion RESTART IDENTITY;
TRUNCATE TABLE description RESTART IDENTITY;
TRUNCATE TABLE recommendation RESTART IDENTITY;
TRUNCATE TABLE content RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;
