# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: 체크아웃
      uses: actions/checkout@v2
    
    - name: JDK 11 설치
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.8

    - name: gradlew 권한 설정
      run: chmod +x gradlew
      
    - name: 빌드
      run: ./gradlew build
      
    - name: 소스코드 업로드
      uses: actions/upload-artifact@v2
      with:
        name: source
        path: .
        
  deploy-master:
    needs: [ build ]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - name: 소스코드 다운로드
        uses: actions/download-artifact@v2
        with:
          name: source

      - name: aws 세팅
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3 업로드
        run: aws deploy push --application-name moa --s3-location s3://moa-backend/deploy/build.zip --source .

      - name: code deploy
        run: aws deploy create-deployment --application-name moa --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name moa-deploy-group --s3-location bucket=moa-backend,bundleType=zip,key=deploy/build.zip
